### PR TITLE
Initial README

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Review by mirceanis — COMMENTED** [review]
Not sure if I'm late to the game with this question, why not use bivrost plugin?

https://github.com/gnosis/bivrost-kotlin

**Comment by ligi** [comment]
e.g. because of this:
 * https://github.com/gnosis/bivrost-kotlin/issues/56

**Comment by mirceanis** [comment]
Correct, but I think it is worth fixing that with a PR, rather than a new lib.
Of course, multiple alternatives to solve a problem are good, so I would welcome an addition to the komputing space.
I'm asking out of a concern about the maintenance overhead.

**Comment by ligi** [comment]
Yea - I was considering doing it as a PR to bivrost-kotlin. An if the android coupling would have been the only thing this would have been the way to go most likely. But another big topic was the type system - I needed something that worked with kethereum types (e.g. address) - and changing this in bivrost would have been ugly and perhaps not even merged upstream. Also please have a look at both codebases. I think kethabi turned out quite nice so I do not regret the decision. Also happy to take on the maintenance overhead in this case.

**Pull request merged**
